# Generated by Django 4.2.2 on 2023-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdsoproject', '0004_alter_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
