# Generated by Django 4.2.2 on 2023-06-26 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdsoproject', '0010_remove_signup_department_remove_signup_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
